config/routes.rb
Sc2leagueengine::Application.routes.draw do

  resources :matches

  resources :games

  resources :players

  resources :maps

  devise_for :admins
  devise_for :teams

  root :to => "home#index"

  namespace :team do
    root :to => "team#home"
  end

end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @maps }
    end
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
    @map = Map.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @map }
    end
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = Map.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @map }
    end
  end

  # GET /maps/1/edit
  def edit
    @map = Map.find(params[:id])
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(params[:map])

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, :notice => 'Map was successfully created.' }
        format.json { render :json => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.json { render :json => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update
    @map = Map.find(params[:id])

    respond_to do |format|
      if @map.update_attributes(params[:map])
        format.html { redirect_to @map, :notice => 'Map was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map = Map.find(params[:id])
    @map.destroy

    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :ok }
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @maps.each do |map| %>
  <tr>
    <td><%= map.name %></td>
    <td><%= link_to 'Show', map %></td>
    <td><%= link_to 'Edit', edit_map_path(map) %></td>
    <td><%= link_to 'Destroy', map, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @map.name %>
</p>


<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>