config/routes.rb
Sc2leagueengine::Application.routes.draw do

  resources :matches

  resources :games

  resources :players

  resources :maps

  devise_for :admins
  devise_for :teams

  root :to => "home#index"

  namespace :team do
    root :to => "team#home"
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :match
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, :notice => 'Game was successfully created.' }
        format.json { render :json => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, :notice => 'Game was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :ok }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playerA_id %><br />
    <%= f.number_field :playerA_id %>
  </div>
  <div class="field">
    <%= f.label :playerB_id %><br />
    <%= f.number_field :playerB_id %>
  </div>
  <div class="field">
    <%= f.label :winner_id %><br />
    <%= f.number_field :winner_id %>
  </div>
  <div class="field">
    <%= f.label :map_id %><br />
    <%= f.number_field :map_id %>
  </div>
  <div class="field">
    <%= f.label :match %><br />
    <%= f.text_field :match %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Playera</th>
    <th>Playerb</th>
    <th>Winner</th>
    <th>Map</th>
    <th>Match</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.playerA_id %></td>
    <td><%= game.playerB_id %></td>
    <td><%= game.winner_id %></td>
    <td><%= game.map_id %></td>
    <td><%= game.match %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Playera:</b>
  <%= @game.playerA_id %>
</p>

<p>
  <b>Playerb:</b>
  <%= @game.playerB_id %>
</p>

<p>
  <b>Winner:</b>
  <%= @game.winner_id %>
</p>

<p>
  <b>Map:</b>
  <%= @game.map_id %>
</p>

<p>
  <b>Match:</b>
  <%= @game.match %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>