config/routes.rb
Sc2leagueengine::Application.routes.draw do

  resources :matches

  resources :games

  resources :players

  resources :maps

  devise_for :admins
  devise_for :teams

  root :to => "home#index"

  namespace :team do
    root :to => "team#home"
  end

end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, :notice => 'Match was successfully created.' }
        format.json { render :json => @match, :status => :created, :location => @match }
      else
        format.html { render :action => "new" }
        format.json { render :json => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, :notice => 'Match was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :ok }
    end
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teamA_id %><br />
    <%= f.number_field :teamA_id %>
  </div>
  <div class="field">
    <%= f.label :teamB_id %><br />
    <%= f.number_field :teamB_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <tr>
    <th>Teama</th>
    <th>Teamb</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.teamA_id %></td>
    <td><%= match.teamB_id %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Teama:</b>
  <%= @match.teamA_id %>
</p>

<p>
  <b>Teamb:</b>
  <%= @match.teamB_id %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>